FROM fzu-huang/docker-xpra-minimal

LABEL version="0.5"
LABEL maintainer="fzu-huang"

# skip interactive configuration dialogs
ENV DEBIAN_FRONTEND noninteractive

# add winswitch repository and install Xpra
RUN apt-get update && \
    apt-get install -y --no-install-recommends xpra-html5 python3-requests && \
    rm -rf /var/lib/apt/lists/*

# copy xpra config file
COPY ./xpra.conf.html5 /etc/xpra/xpra.conf

# set default password
ENV XPRA_PASSWORD xpra

# expose xpra HTML5 client port
EXPOSE 14500
